
["Global Options"]
	#If TRUE, Redstone Flux will act as its own energy system and will NOT be interoperable with 'Forge Energy' - only enable this if you absolutely know what you are doing and want the Thermal Series to use a unique energy system.
	"Standalone Redstone Flux" = false
	#If TRUE, most Thermal Blocks will retain Energy when dropped.
	#This setting does not control ALL blocks.
	"Blocks Retain Energy" = true
	#If TRUE, most Thermal Blocks will retain Inventory Contents when dropped.
	#This setting does not control ALL blocks.
	"Blocks Retain Inventory" = false
	#If TRUE, most Thermal Blocks will retain Tank Contents when dropped.
	#This setting does not control ALL blocks.
	"Blocks Retain Tank Contents" = false
	#If TRUE, Thermal Blocks will retain Augments when dropped.
	"Blocks Retain Augments" = true
	#If TRUE, Thermal Blocks will retain Redstone Control configuration when dropped.
	"Blocks Retain Redstone Control" = true
	#If TRUE, Thermal Blocks will retain Side configuration when dropped.
	"Blocks Retain Side Configuration" = true
	#If TRUE, Thermal Blocks will retain Transfer Control configuration when dropped.
	"Blocks Retain Transfer Control" = true

[Tools]

	[Tools.Satchel]
		#A list of Items by Resource Location which are NOT allowed in Satchels.
		Denylist = ["thermal:satchel", "minecraft:shulker_box", "minecraft:white_shulker_box", "minecraft:orange_shulker_box", "minecraft:magenta_shulker_box", "minecraft:light_blue_shulker_box", "minecraft:yellow_shulker_box", "minecraft:lime_shulker_box", "minecraft:pink_shulker_box", "minecraft:gray_shulker_box", "minecraft:light_gray_shulker_box", "minecraft:cyan_shulker_box", "minecraft:purple_shulker_box", "minecraft:blue_shulker_box", "minecraft:brown_shulker_box", "minecraft:green_shulker_box", "minecraft:red_shulker_box", "minecraft:black_shulker_box"]

[Mobs]
	#If TRUE, the Basalz Mob is enabled.
	Basalz = true
	#If TRUE, the Blitz Mob is enabled.
	Blitz = true
	#If TRUE, the Blizz Mob is enabled.
	Blizz = true
	#If TRUE, the Blitz can occasionally call down lightning bolts.
	"Blitz Lightning" = true

[Augments]
	#If TRUE, Side Reconfiguration is enabled by default on most augmentable blocks which support it.
	#If FALSE, an augment is required.
	#This setting does not control ALL blocks.
	"Default Side Reconfiguration" = true
	#If TRUE, Redstone Control is enabled by default on most augmentable blocks which support it.
	#If FALSE, an augment is required.
	#This setting does not control ALL blocks.
	"Default Redstone Control" = true
	#If TRUE, XP Storage is enabled by default on most augmentable blocks which support it.
	#If FALSE, an augment is required.
	#This setting does not control ALL blocks.
	"Default XP Storage" = false

[Villagers]
	#If TRUE, trades will be added to various Villagers.
	"Enable Villager Trades" = true
	#If TRUE, trades will be added to the Wandering Trader.
	"Enable Wandering Trader Trades" = true

