
[naturalSpawningDepth]
	#The specified mob will only naturally spawn below the specified y-level. This is so certain mobs are cave-exclusive by default.
	"Petriman Spawning Depth" = 55.0
	"Silverking Spawning Depth" = -10.0
	"Crawler Spawning Depth" = 65.0
	"Troll Spawning Depth" = -10.0
	"Vampire Spawning Depth" = -10.0
	"Intruder Spawning Depth" = 35.0
	"Cockatrice Spawning Depth" = 60.0

[mobReplacement]
	"Petriman Spawns Alongside Zombie" = 1.0
	"Silverking Spawns Alongside Spider" = 0.4
	"Crawler/Intruder Spawns Alongside Creeper" = 0.3
	"Vampire Spawns Alongside Skeleton" = 0.75
	"Troll Spawns Alongside Enderman" = 1.0
	#(This is the only way in which Cinders will ever spawn - Disable at your own risk!)
	"Cinder Replaces Blaze" = 0.2
	"Tarantula Replaces Dripstone Caves Mobs" = 1.0
	"Scorpion Replaces Desert Spider" = 1.0
	"Random Enemy Expansion Zombie Replacement" = 0.0
	"Illagers Replace Villagers" = 0.0
	"Ravagers Replace Iron Golems" = 0.0
	#Ravagers are replaced with Marauders on spawn, but only if they spawn in water
	"Marauders Replace Water-bound Ravagers" = 1.0
	#(This is the only way in which Sputters naturally spawn - Disable at your own risk!)
	"Sputter Spawns Alongside Strider" = 0.35
	"Hornet Replaces Vex" = 0.0
	"Skeleton Horseman Addition" = 0.03

[mobReplacementDepth]
	"Petriman Spawns Alongside Zombie Depth" = 55.0
	"Silverking Spawns Alongside Spider Depth" = -10.0
	"Crawler/Intruder Spawns Alongside Creeper Depth" = -10.0
	"Vampire Spawns Alongside Skeleton Depth" = -10.0
	"Troll Spawns Alongside Enderman Depth" = -10.0

[hatWearerSpawning]
	#Some Zombies and Skeletons will spawn wearing certain special gear. edit the minecraft:is_meatury tag to choose what biomes these mobs spawn in.
	"Meat Head Wearer Spawning" = 0.01
	"Headbitten Wearer Spawning" = 0.01
	"Slimehead Wearer Spawning" = 0.01
	"Spiderlatch Wearer Spawning" = 0.005
	"Silverhead Wearer Spawning" = 0.005
	"Horsehead Wearer Spawning" = 0.005
	"Miniwither Wearer Spawning" = 0.001
	"Flutterfliers Wearer Spawning" = 0.003
	"Phantasm Wearer Spawning" = 0.005
	"Spectral Wearer Spawning" = 0.01
	"Brutish Garment Wearer Spawning" = 0.001
	"Bull Skull Wearer Spawning" = 0.01
	"Bane Mask Wearer Spawning" = 0.01
	"Gladling Wearer Spawning" = 0.005
	"Guardsmask Wearer Spawning" = 0.005
	#Champion Mobs Wearing Hats are different from regular Champion spawns, in that they can spawn at different levels and also come with Absorption as a permanent effect
	"Headwear-wearing mobs always spawn as Champions" = true
	"Resting Vigor Wearer Spawning" = 0.01
	"Cockatrice Head Wearer Spawning" = 0.001

[armorWearerSpawning]
	"Leather Wearer Spawning" = 0.03
	"Chainmail Wearer Spawning" = 0.02
	"Iron Wearer Spawning" = 0.01
	"Gold Wearer Spawning" = 0.007
	"Diamond Wearer Spawning" = 0.004
	"Netherite Wearer Spawning" = 0.001
	"Emerald Wearer Spawning" = 0.007
	"Amethyst Wearer Spawning" = 0.007

[miscOptions]
	"Punching Ram Drops Wool Chance" = 0.0
	"Wandering Trader becomes Illusioner on-death Chance" = 0.95
	"Mobs Sometimes Spawn With Varying Speed Chance" = 0.5
	"Skeletons Switch Weapons Mid-Fight Chance" = 0.2
	"Flies Spawn From Killed Zombies Chance" = 0.02
	"Pillagers Spawn with Reaver Chance" = 0.16
	#0 fully disables it, 1 fully enables it, and an inbetween acts as a percentage chance for it to work (0.13 being 13%, for example.)
	"Baby Zombie Spawning" = 0.13
	"Baby Zombie Health Amount" = 2.0
	"Phantom Health Amount" = 6.0
	#Chance a Zombified Piglin will spawn hostile
	"Hostile Zombified Piglin Chance" = 0.01
	"Players move faster while charging a bow" = false
	#Players gain the Streak effect upon killing two mobs in succession, giving them special effects defined in an mcfunction (Speed and Strength by default)
	"Streak Effect" = false
	#Number of seconds until a Streak is lost and reset
	"Streak Effect Duration" = 10.0
	#Skeletons become susceptible to lethal amounts of extra damage if shot with an arrow shortly after firing their bow. Enabling faster movement whilst charging a bow with this is option enabled is recommended.
	"Skeleton Quick Draw Effect" = true
	#Just for fun!
	"All Attacks Knock You Backwards" = false
	#Chance landing a critical strike on a bow-weilding Skeleton will disarm them.
	"Skeleton Bow Break on Crit Chance" = 0.33
	"Phantom's Get Groundbound When Hurt Duration (In Seconds)" = 3.0
	#Phantoms spawn bigger than normal, making them easier to hit (but allowing them to deal more damage, too.)
	"Random Phantom Size" = true
	"Skeleton Death Kills Skeleton Horses Chance" = 0.95
	"Eyestalkers are Hostile by default" = false

[effectSpawning]
	"Chance of Strength effect applied on mob-spawn" = 0.01
	"Chance of Speed effect applied on mob-spawn" = 0.01
	"Chance of Resistance effect applied on mob-spawn" = 0.01
	"Chance of Haste effect applied on mob-spawn" = 0.01
	"Chance of Fire Resistance effect applied on mob-spawn" = 0.01
	"Chance of a mob being a Champion upon spawning" = 0.0

