#Air qualities at different heights in different dimensions.
#The syntax is the dimension's resource location, the "default" air level in that dimension,
#then any number of height:airlevel pairs separated by commas.
#The air will have that quality starting at that height and above (until the next entry).
#The entries must be in ascending order of height.
#If a dimension doesn't have an entry here, it'll be assumed to be green everywhere.
dimensions = ["minecraft:overworld=yellow,0:green,128:yellow", "minecraft:the_nether=yellow", "minecraft:the_end=red"]
#Entities that can always breathe.
#This is in addition to entities where `.canBreatheUnderwater()` returns true (so, fish and undead),
#and invulnerable players.
alwaysBreathingEntities = ["enemyexpansion:a", "enemyexpansion:angler", "enemyexpansion:baker", "enemyexpansion:banedasher", "enemyexpansion:biter", "enemyexpansion:boar", "enemyexpansion:bouncer", "enemyexpansion:bull", "enemyexpansion:cakerover", "enemyexpansion:caster", "enemyexpansion:cinder", "enemyexpansion:cockatrice", "enemyexpansion:crawler", "enemyexpansion:direwolf", "enemyexpansion:dragonfly", "enemyexpansion:dreadnought", "enemyexpansion:equestrian", "enemyexpansion:errant", "enemyexpansion:eyestalker", "enemyexpansion:fish_carrier", "enemyexpansion:flutterfly", "enemyexpansion:fly", "enemyexpansion:frigid", "enemyexpansion:gabble", "enemyexpansion:gallant", "enemyexpansion:ghoul", "enemyexpansion:gladilad", "enemyexpansion:gladius", "enemyexpansion:goblin", "enemyexpansion:goblin_fear", "enemyexpansion:guardsman", "enemyexpansion:halflife", "enemyexpansion:hornet", "enemyexpansion:huntsmanskeleton", "enemyexpansion:intruder", "enemyexpansion:invisicreeper", "enemyexpansion:kelpie", "enemyexpansion:ladybug", "enemyexpansion:marauder", "enemyexpansion:meature", "enemyexpansion:orb", "enemyexpansion:petrifiedtroll", "enemyexpansion:petriman", "enemyexpansion:pheromone_summon", "enemyexpansion:piecrab", "enemyexpansion:propeller", "enemyexpansion:ram", "enemyexpansion:ramsheared", "enemyexpansion:rancher", "enemyexpansion:reaver", "enemyexpansion:rooster", "enemyexpansion:scorpion", "enemyexpansion:senior", "enemyexpansion:silverking", "enemyexpansion:silverpet", "enemyexpansion:slugger", "enemyexpansion:spectre", "enemyexpansion:sprinter", "enemyexpansion:sputter", "enemyexpansion:starved", "enemyexpansion:tarantula", "enemyexpansion:troll", "enemyexpansion:vampire", "enemyexpansion:vigor", "enemyexpansion:wasp", "enemyexpansion:wolfsbane", "enemyexpansion:zadybug", "enemyexpansion:zobgoblin", "minecraft:armor_stand", "minecraft:enderman", "minecraft:endermite", "minecraft:shulker", "minecraft:strider", "minecraft:ghast", "minecraft:piglin", "minecraft:hoglin", "minecraft:piglin_brute", "minecraft:blaze", "minecraft:magma_cube", "minecraft:ender_dragon", "minecraft:wither"]
#Whether to allow right-clicking torches to make them spray particle effects
enableSignalTorches = true
#How much air a Drowned attack removes
#Range: > -2147483648
drownedChoking = 100

[Ranges]
	#The radius a soul torch projects a bubble of blue air around it
	#Range: 0.0 ~ 32.0
	soulTorchRange = 2.0
	#The radius a soul fire projects a bubble of blue air around it
	#Range: 0.0 ~ 32.0
	soulFireRange = 5.0
	#The radius a soul campfire projects a bubble of blue air around it
	#Range: 0.0 ~ 32.0
	soulCampfireRange = 9.0
	#The radius lava blocks project a bubble of red air around it
	#Range: 0.0 ~ 32.0
	lavaRange = 5.0
	#The radius nether portal blocks project a bubble of green air around it
	#Range: 0.0 ~ 32.0
	netherPortalRange = 5.0

